// apps/mfe-app-janus-team/src/components/Navbar.vue
<template>
    <nav class="navbar">
        <ul class="navbar-list container mx-auto">
            <li class="navbar-item">
            <router-link class="navbar-link" to="/">Home</router-link>
            </li>
            <li class="navbar-item">
            <router-link class="navbar-link" to="/about">Sobre</router-link>
            </li>
            <li class="navbar-item">
            <router-link class="navbar-link" to="/material">Materiais</router-link>
            </li>
        </ul>
    </nav>
</template>

<style scoped>
.navbar {
    background-color: #333;
    padding: 1rem;
}

.navbar-list {
    list-style-type: none;
    display: flex;
}

.navbar-item {
    margin: 0;
}

.navbar-link {
    color: white;
    text-decoration: none;
    font-weight: bold;
}

.navbar-link:hover {
    text-decoration: underline;
}
</style>

// apps/mfe-app-jupiter-team/src/components/Navbar.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import styles from './Navbar.module.css';

const Navbar: React.FC = () => {
  return (
    <nav className={styles['navbar']}>
      <ul className={`${styles['navbar-list']} container mx-auto`}>
        <li className={styles['navbar-item']}>
          <Link to="/" className={styles['navbar-link']}>
            Home
          </Link>
        </li>
        <li className={styles['navbar-item']}>
          <Link to="/about" className={styles['navbar-link']}>
            Sobre
          </Link>
        </li>
        <li className={styles['navbar-item']}>
          <Link to="/material" className={styles['navbar-link']}>
            Materiais
          </Link>
        </li>
      </ul>
    </nav>
  );
};

export default Navbar;
